{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import random\n",
    "from typing import List\n",
    "import twscrape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "def set_up_directories(keyword_eng: str, year: str):\n",
    "    os.mkdir(keyword_eng + \"_\" + year)\n",
    "\n",
    "    # single digit month\n",
    "    for i in range(1,10):\n",
    "        path = keyword_eng + \"_\" + year + \"/\" + \"0\" + str(i)\n",
    "        os.mkdir(path) \n",
    "\n",
    "    # double digit month\n",
    "    for j in range(10,13):\n",
    "        path = keyword_eng + \"_\" + year + \"/\" + str(j)\n",
    "        os.mkdir(path) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "set_up_directories(\"zainichi\", \"2022\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# remove directories if needed\n",
    "!rm -rf zainichi_2022/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# scrape randomly sampled tweets for 10 days in given month\n",
    "def scrape_month_sampled_tweets(year: str, months: List[str], days_in_month: int, keyword_jp: str, keyword_eng: str):\n",
    "    range_days = list(range(1,days_in_month+1))\n",
    "    range_times = list(range(0,24))\n",
    "    dir_path = year if keyword_eng == \"\" else keyword_eng + \"_\" + year\n",
    "\n",
    "    # sample 10 random days and times of day for each month\n",
    "    for m in months: \n",
    "        month_path = dir_path + \"/\" + m\n",
    "        days = sorted(random.sample(range_days, k=10))   # random days of month (no replacement)\n",
    "        times = random.choices(range_times, k=10)   # random hours of day (replacement)\n",
    "        \n",
    "        # scrape tweets for the 10 picked days and times\n",
    "        for t in range(10):     \n",
    "            day = \"0\" + str(days[t]) if days[t] < 10 else str(days[t])\n",
    "            time = \"0\" + str(times[t]) if times[t] < 10 else str(times[t])\n",
    "            day_path = month_path + \"/\" + year + \"-\" + m + \"-\" + day + \".txt\"\n",
    "            command = 'twscrape search \"' + keyword_jp + ' since:' + year + '-' + m + '-' + day + '_' + time + ':00:00_UTC lang:ja\"　> ' + day_path + ' --limit=4500'\n",
    "            # os.system(command)\n",
    "            print(command)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "# scrape random sample of tweets (general content or keyword-search) from given year\n",
    "def scrape_year_sampled_tweets(year: str, keyword_jp=\"\", keyword_eng=\"\"):\n",
    "    # 28 day months\n",
    "    scrape_month_sampled_tweets(year,[\"02\"], 28, keyword_jp, keyword_eng)    # omit leap year 29th days for simplicity...?\n",
    "\n",
    "    # 30 day months\n",
    "    months_30 = [\"04\",\"06\",\"09\",\"11\"]\n",
    "    scrape_month_sampled_tweets(year,months_30, 30, keyword_jp, keyword_eng)\n",
    "\n",
    "    # 31 day months\n",
    "    months_31 = [\"01\",\"03\",\"05\",\"07\",\"08\",\"10\",\"12\"]\n",
    "    scrape_month_sampled_tweets(year,months_31, 31, keyword_jp, keyword_eng)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "def concatenate_general_txt_files(year: str, keyword_eng=\"\"):\n",
    "  # concatenate .txt files into one file per month\n",
    "  for root, dirs, files in os.walk(\"./\" + year):\n",
    "      for name in dirs:\n",
    "        month_path = os.path.join(root, name)\n",
    "        os.system(\"cat \" + month_path + \"/*.txt > \" + name + \".txt\")\n",
    "  \n",
    "  # concatenate month .txt files into one file for the year\n",
    "  os.system(\"cat \" + year + \"-*.txt > \" + keyword_eng + \"_\" + year + \"-all.txt\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "scrape_year_sampled_tweets(\"2022\")\n",
    "concatenate_general_txt_files(\"2022\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# scrape randomly sampled tweets for 10 days in given month\n",
    "def scrape_keyword_month_tweets(year: str, months: List[str], days_in_month: int, keyword_jp: str, keyword_eng: str):\n",
    "    dir_path = year if keyword_eng == \"\" else keyword_eng + \"_\" + year\n",
    "\n",
    "    # sample 10 random days and times of day for each month\n",
    "    for m in months: \n",
    "        command = 'twscrape search \"' + keyword_jp + ' since:' + year + '-' + m + '-01_00:00:00_UTC until:' + year + '-' + m + '-' + str(days_in_month) + '_23:59:59_UTC lang:ja\"　> ' + keyword_eng + '_' + year + '/' + m + '.txt'\n",
    "        os.system(command)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "# scrape all tweets containing keyword in given year\n",
    "def scrape_keyword_sampled_tweets(year: str, keyword_jp: str, keyword_eng: str):\n",
    "    # os.mkdir(keyword_eng + \"_\" + year) \n",
    "\n",
    "    # 28 day months\n",
    "    scrape_keyword_month_tweets(year,[\"02\"], 28, keyword_jp, keyword_eng)    # omit leap year 29th days for simplicity...?\n",
    "\n",
    "    # 30 day months\n",
    "    months_30 = [\"04\",\"06\",\"09\",\"11\"]\n",
    "    scrape_keyword_month_tweets(year,months_30, 30, keyword_jp, keyword_eng)\n",
    "\n",
    "    # 31 day months\n",
    "    months_31 = [\"01\",\"03\",\"05\",\"07\",\"08\",\"10\",\"12\"]\n",
    "    scrape_keyword_month_tweets(year,months_31, 31, keyword_jp, keyword_eng)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "def concatenate_keyword_txt_files(year: str, keyword_eng=\"\"):\n",
    "  # concatenate month .txt files into one file for the year\n",
    "  os.system(\"cat \" + keyword_eng + \"_\" + year + \"/\" + \"*.txt > \" + keyword_eng + \"_\" + year + \".txt\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-03-12 20:42:43.213 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 20:51:39\n",
      "2024-03-12 20:54:21.106 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-12 22:42:49.096 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 22:49:23\n",
      "2024-03-12 22:49:24.743 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_3 on queue SearchTimeline\n",
      "2024-03-12 22:50:06.204 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 22:50:15\n",
      "2024-03-12 22:50:16.225 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_4 on queue SearchTimeline\n",
      "2024-03-12 22:52:07.815 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 22:52:13\n",
      "2024-03-12 22:52:17.834 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-12 22:52:56.659 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 22:53:14\n",
      "2024-03-12 22:53:16.691 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_6 on queue SearchTimeline\n",
      "2024-03-12 22:54:00.721 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 22:54:38\n",
      "2024-03-12 22:54:40.785 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_research on queue SearchTimeline\n",
      "2024-03-12 22:55:24.565 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 22:55:36\n",
      "2024-03-12 22:55:39.581 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account nlp542381374579 on queue SearchTimeline\n",
      "2024-03-13 08:01:33.601 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 08:08:19\n",
      "2024-03-13 08:08:24.141 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-13 08:09:10.690 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 08:09:26\n",
      "2024-03-13 08:09:30.736 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_3 on queue SearchTimeline\n"
     ]
    }
   ],
   "source": [
    "# zainichi korean set\n",
    "scrape_keyword_sampled_tweets(\"2022\", \"在日コリアン\", \"zainichi\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "concatenate_keyword_txt_files(\"2022\", \"zainichi\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-03-13 23:54:00.375 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 23:56:34\n",
      "2024-03-13 23:56:36.562 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-13 23:57:36.571 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 23:58:27\n",
      "2024-03-13 23:58:31.750 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_3 on queue SearchTimeline\n",
      "2024-03-14 00:00:18.336 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:01:22\n",
      "2024-03-14 00:02:37.450 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_5 on queue SearchTimeline\n",
      "2024-03-14 00:09:36.593 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:11:36\n",
      "2024-03-14 00:11:41.844 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-14 00:12:28.301 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:13:32\n",
      "2024-03-14 00:13:33.425 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_3 on queue SearchTimeline\n",
      "2024-03-14 00:16:07.529 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:17:45\n",
      "2024-03-14 00:17:47.706 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_5 on queue SearchTimeline\n",
      "2024-03-14 00:18:43.373 | WARNING  | twscrape.queue_client:_check_rep:186 - API unknown error: 200 - 11/50 - jp_nlp_res_5 - (0) Something went wrong\n",
      "2024-03-14 00:18:56.263 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at now\n",
      "2024-03-14 00:19:01.277 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_6 on queue SearchTimeline\n",
      "2024-03-14 00:19:59.585 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:20:45\n",
      "2024-03-14 00:20:49.674 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_research on queue SearchTimeline\n",
      "2024-03-14 00:32:22.851 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:32:47\n",
      "2024-03-14 00:32:52.910 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_5 on queue SearchTimeline\n",
      "2024-03-14 00:33:33.262 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:34:02\n",
      "2024-03-14 00:34:03.317 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_6 on queue SearchTimeline\n",
      "2024-03-14 00:34:41.349 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:36:07\n",
      "2024-03-14 00:36:11.495 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_research on queue SearchTimeline\n",
      "2024-03-14 00:36:48.274 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:44:07\n",
      "2024-03-14 00:44:08.980 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-14 00:44:46.344 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:44:47\n",
      "2024-03-14 00:44:51.355 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_3 on queue SearchTimeline\n",
      "2024-03-14 00:47:30.744 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:47:53\n",
      "2024-03-14 00:47:55.788 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_5 on queue SearchTimeline\n",
      "2024-03-14 00:48:34.993 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:49:03\n",
      "2024-03-14 00:49:05.042 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_6 on queue SearchTimeline\n",
      "2024-03-14 00:49:46.220 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:51:11\n",
      "2024-03-14 00:51:16.376 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_research on queue SearchTimeline\n",
      "2024-03-14 00:51:55.550 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:59:09\n",
      "2024-03-14 00:59:11.351 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-14 00:59:50.663 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:59:51\n",
      "2024-03-14 00:59:55.671 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_3 on queue SearchTimeline\n",
      "2024-03-14 01:02:34.393 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 01:02:56\n",
      "2024-03-14 01:02:59.439 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_5 on queue SearchTimeline\n",
      "2024-03-14 01:03:43.417 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 01:04:05\n",
      "2024-03-14 01:04:08.457 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_6 on queue SearchTimeline\n",
      "2024-03-14 01:04:46.532 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 01:06:16\n",
      "2024-03-14 01:06:21.691 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_research on queue SearchTimeline\n",
      "2024-03-14 01:07:05.573 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 01:14:11\n",
      "2024-03-14 01:14:16.288 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-14 01:14:55.545 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at now\n",
      "2024-03-14 01:15:00.557 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_3 on queue SearchTimeline\n",
      "2024-03-14 01:16:55.668 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at now\n",
      "2024-03-14 01:17:00.680 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account nlp654242235435 on queue SearchTimeline\n",
      "2024-03-14 01:17:38.671 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 01:17:59\n",
      "2024-03-14 01:18:03.727 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_5 on queue SearchTimeline\n",
      "2024-03-14 01:18:40.452 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 01:19:08\n",
      "2024-03-14 01:19:10.504 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_6 on queue SearchTimeline\n",
      "2024-03-14 01:19:48.233 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 01:21:21\n",
      "2024-03-14 01:21:23.415 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_research on queue SearchTimeline\n",
      "2024-03-14 01:21:59.329 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 01:29:16\n",
      "2024-03-14 01:29:20.077 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-14 01:29:56.936 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 01:30:00\n",
      "2024-03-14 01:30:01.947 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_3 on queue SearchTimeline\n",
      "2024-03-14 01:30:38.342 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 01:30:40\n",
      "2024-03-14 01:30:43.353 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_4 on queue SearchTimeline\n",
      "2024-03-14 01:31:56.785 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 01:32:00\n",
      "2024-03-14 01:32:01.796 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account nlp654242235435 on queue SearchTimeline\n",
      "2024-03-14 01:32:40.247 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 01:33:03\n",
      "2024-03-14 01:33:05.292 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_5 on queue SearchTimeline\n",
      "2024-03-14 01:33:44.101 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 01:34:10\n",
      "2024-03-14 01:34:14.150 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_6 on queue SearchTimeline\n",
      "2024-03-14 01:34:53.123 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 01:36:23\n",
      "2024-03-14 01:36:28.278 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_research on queue SearchTimeline\n",
      "2024-03-14 01:37:07.118 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 01:44:20\n",
      "2024-03-14 01:44:23.965 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-14 01:45:02.095 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at now\n",
      "2024-03-14 01:45:07.102 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_3 on queue SearchTimeline\n",
      "2024-03-14 01:55:33.220 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 01:59:24\n",
      "2024-03-14 01:59:28.564 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-14 02:00:06.199 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 02:00:07\n",
      "2024-03-14 02:00:11.209 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_3 on queue SearchTimeline\n",
      "2024-03-14 02:03:01.435 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 02:07:40\n",
      "2024-03-14 02:07:41.855 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_5 on queue SearchTimeline\n",
      "2024-03-14 02:08:58.742 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 02:09:09\n",
      "2024-03-14 02:09:13.768 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_research on queue SearchTimeline\n",
      "2024-03-14 02:09:51.724 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 02:09:55\n",
      "2024-03-14 02:09:56.734 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account nlp654242235435 on queue SearchTimeline\n",
      "2024-03-14 02:10:34.684 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 02:14:28\n",
      "2024-03-14 02:14:30.074 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-14 02:15:09.801 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 02:15:11\n",
      "2024-03-14 02:15:14.811 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_3 on queue SearchTimeline\n",
      "2024-03-14 02:15:51.041 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 02:16:42\n",
      "2024-03-14 02:16:46.112 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_4 on queue SearchTimeline\n",
      "2024-03-14 02:18:03.013 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 02:22:42\n",
      "2024-03-14 02:22:43.406 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_5 on queue SearchTimeline\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 154, in _connect\n",
      "    stream = await stream.start_tls(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 66, in start_tls\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectTimeout\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectTimeout\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 122, in _connect\n",
      "    stream = await self._network_backend.connect_tcp(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/auto.py\", line 30, in connect_tcp\n",
      "    return await self._backend.connect_tcp(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 112, in connect_tcp\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectTimeout\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectTimeout\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 154, in _connect\n",
      "    stream = await stream.start_tls(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 66, in start_tls\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectTimeout\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectTimeout\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 154, in _connect\n",
      "    stream = await stream.start_tls(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 66, in start_tls\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectTimeout\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectTimeout\n",
      "2024-03-14 03:31:27.587 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 03:41:24\n",
      "2024-03-14 03:41:28.576 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-14 03:43:34.486 | WARNING  | twscrape.queue_client:_check_rep:186 - API unknown error: 200 - 36/50 - jp_nlp_res_5 - (0) OverCapacity: Unspecified\n",
      "2024-03-14 03:46:35.948 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 03:56:28\n",
      "2024-03-14 04:02:12.563 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-14 04:07:18.393 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 04:17:13\n",
      "2024-03-14 04:17:15.420 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-14 04:41:07.652 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 04:50:56\n",
      "2024-03-14 05:05:49.547 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-14 06:55:15.506 | WARNING  | twscrape.queue_client:_check_rep:186 - API unknown error: 200 -  1/50 - nlp542381374579 - (0) OverCapacity: Unspecified\n",
      "2024-03-14 06:55:56.176 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 07:05:31\n",
      "2024-03-14 07:05:36.984 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-14 07:08:31.625 | WARNING  | twscrape.queue_client:_check_rep:186 - API unknown error: 200 - 43/50 - jp_nlp_res_6 - (29) Timeout: Unspecified\n",
      "2024-03-14 07:11:10.018 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 07:20:37\n",
      "2024-03-14 07:34:24.660 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-14 07:34:57.498 | WARNING  | twscrape.queue_client:_check_rep:186 - API unknown error: 200 - 14/50 - jp_nlp_res_2 - (29) Timeout: Unspecified\n",
      "2024-03-14 08:17:12.283 | WARNING  | twscrape.queue_client:_check_rep:186 - API unknown error: 200 - 36/50 - jp_nlp_res_4 - (29) Timeout: Unspecified\n",
      "2024-03-14 08:43:57.789 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 08:49:43\n",
      "2024-03-14 08:54:20.732 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-14 09:01:34.488 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 09:09:21\n",
      "2024-03-14 09:09:54.571 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "2024-03-14 23:07:40.343 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 23:11:44\n",
      "2024-03-14 23:11:45.745 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_3 on queue SearchTimeline\n",
      "2024-03-14 23:12:44.737 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 23:16:10\n",
      "2024-03-14 23:16:35.942 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 122, in _connect\n",
      "    stream = await self._network_backend.connect_tcp(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/auto.py\", line 30, in connect_tcp\n",
      "    return await self._backend.connect_tcp(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 112, in connect_tcp\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 122, in _connect\n",
      "    stream = await self._network_backend.connect_tcp(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/auto.py\", line 30, in connect_tcp\n",
      "    return await self._backend.connect_tcp(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 112, in connect_tcp\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 154, in _connect\n",
      "    stream = await stream.start_tls(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 66, in start_tls\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectTimeout\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectTimeout\n"
     ]
    }
   ],
   "source": [
    "# ainu\n",
    "os.mkdir(\"ainu_2022\")\n",
    "scrape_keyword_sampled_tweets(\"2022\", \"アイヌ\", \"ainu\")\n",
    "concatenate_keyword_txt_files(\"2022\", \"ainu\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 154, in _connect\n",
      "    stream = await stream.start_tls(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 66, in start_tls\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectTimeout\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectTimeout\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 154, in _connect\n",
      "    stream = await stream.start_tls(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 66, in start_tls\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectTimeout\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectTimeout\n"
     ]
    }
   ],
   "source": [
    "# ryukyu\n",
    "os.mkdir(\"ryukyujin_2022\")\n",
    "scrape_keyword_sampled_tweets(\"2022\", \"琉球人\", \"ryukyujin\")\n",
    "concatenate_keyword_txt_files(\"2022\", \"ryukyujin\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-03-14 23:45:29.275 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 23:51:39\n",
      "2024-03-14 23:52:05.702 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_2 on queue SearchTimeline\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 122, in _connect\n",
      "    stream = await self._network_backend.connect_tcp(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/auto.py\", line 30, in connect_tcp\n",
      "    return await self._backend.connect_tcp(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 112, in connect_tcp\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known\n",
      "2024-03-15 00:01:20.108 | WARNING  | twscrape.queue_client:_check_rep:186 - API unknown error: 200 - 34/50 - jp_nlp_res_6 - (0) OverCapacity: Unspecified\n",
      "2024-03-15 00:09:20.402 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:13:45\n",
      "2024-03-15 00:13:50.903 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_4 on queue SearchTimeline\n",
      "2024-03-15 00:14:30.132 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:14:44\n",
      "2024-03-15 00:14:45.170 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_5 on queue SearchTimeline\n",
      "2024-03-15 00:15:26.439 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:16:06\n",
      "2024-03-15 00:16:11.504 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_6 on queue SearchTimeline\n",
      "2024-03-15 00:16:48.314 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:21:04\n",
      "2024-03-15 00:21:09.012 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_research on queue SearchTimeline\n",
      "2024-03-15 00:21:43.674 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:21:50\n",
      "2024-03-15 00:21:53.691 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account nlp542381374579 on queue SearchTimeline\n",
      "2024-03-15 00:24:21.686 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:28:51\n",
      "2024-03-15 00:28:52.127 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_4 on queue SearchTimeline\n",
      "2024-03-15 00:29:28.324 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:29:46\n",
      "2024-03-15 00:29:48.351 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_5 on queue SearchTimeline\n",
      "2024-03-15 00:30:24.848 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:31:11\n",
      "2024-03-15 00:31:14.910 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_6 on queue SearchTimeline\n",
      "2024-03-15 00:31:50.889 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:36:09\n",
      "2024-03-15 00:36:11.245 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_research on queue SearchTimeline\n",
      "2024-03-15 00:36:46.750 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:36:53\n",
      "2024-03-15 00:36:56.767 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account nlp542381374579 on queue SearchTimeline\n",
      "2024-03-15 00:39:23.922 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:43:52\n",
      "2024-03-15 00:43:54.291 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_4 on queue SearchTimeline\n",
      "2024-03-15 00:44:31.045 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:44:48\n",
      "2024-03-15 00:44:51.069 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_5 on queue SearchTimeline\n",
      "2024-03-15 00:45:27.729 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:46:15\n",
      "2024-03-15 00:46:17.794 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_6 on queue SearchTimeline\n",
      "2024-03-15 00:46:54.706 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:51:11\n",
      "2024-03-15 00:51:15.144 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_research on queue SearchTimeline\n",
      "2024-03-15 00:51:50.332 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:51:56\n",
      "2024-03-15 00:52:00.348 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account nlp542381374579 on queue SearchTimeline\n",
      "2024-03-15 00:53:11.599 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:53:13\n",
      "2024-03-15 00:53:16.611 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account nlp654242235435 on queue SearchTimeline\n",
      "2024-03-15 00:54:30.901 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:58:54\n",
      "2024-03-15 00:58:56.408 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_4 on queue SearchTimeline\n",
      "2024-03-15 00:59:31.462 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:275 - No account available for queue \"SearchTimeline\". Next available at 00:59:51\n",
      "2024-03-15 00:59:56.488 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:281 - Continuing with account jp_nlp_res_5 on queue SearchTimeline\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 122, in _connect\n",
      "    stream = await self._network_backend.connect_tcp(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/auto.py\", line 30, in connect_tcp\n",
      "    return await self._backend.connect_tcp(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 112, in connect_tcp\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 122, in _connect\n",
      "    stream = await self._network_backend.connect_tcp(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/auto.py\", line 30, in connect_tcp\n",
      "    return await self._backend.connect_tcp(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 112, in connect_tcp\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectTimeout\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectTimeout\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 122, in _connect\n",
      "    stream = await self._network_backend.connect_tcp(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/auto.py\", line 30, in connect_tcp\n",
      "    return await self._backend.connect_tcp(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 112, in connect_tcp\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectTimeout\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectTimeout\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 154, in _connect\n",
      "    stream = await stream.start_tls(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 66, in start_tls\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectTimeout\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectTimeout\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 122, in _connect\n",
      "    stream = await self._network_backend.connect_tcp(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/auto.py\", line 30, in connect_tcp\n",
      "    return await self._backend.connect_tcp(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 112, in connect_tcp\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 122, in _connect\n",
      "    stream = await self._network_backend.connect_tcp(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/auto.py\", line 30, in connect_tcp\n",
      "    return await self._backend.connect_tcp(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 112, in connect_tcp\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 122, in _connect\n",
      "    stream = await self._network_backend.connect_tcp(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/auto.py\", line 30, in connect_tcp\n",
      "    return await self._backend.connect_tcp(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 112, in connect_tcp\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 154, in _connect\n",
      "    stream = await stream.start_tls(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 66, in start_tls\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectTimeout\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectTimeout\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 122, in _connect\n",
      "    stream = await self._network_backend.connect_tcp(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/auto.py\", line 30, in connect_tcp\n",
      "    return await self._backend.connect_tcp(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 112, in connect_tcp\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 373, in handle_async_request\n",
      "    resp = await self._pool.handle_async_request(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 216, in handle_async_request\n",
      "    raise exc from None\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection_pool.py\", line 196, in handle_async_request\n",
      "    response = await connection.handle_async_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n",
      "    raise exc\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n",
      "    stream = await self._connect(request)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_async/connection.py\", line 122, in _connect\n",
      "    stream = await self._network_backend.connect_tcp(**kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/auto.py\", line 30, in connect_tcp\n",
      "    return await self._backend.connect_tcp(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_backends/anyio.py\", line 112, in connect_tcp\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/bin/twscrape\", line 8, in <module>\n",
      "    sys.exit(run())\n",
      "             ^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 206, in run\n",
      "    asyncio.run(main(args))\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 190, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/cli.py\", line 115, in main\n",
      "    async for doc in fn(val, limit=args.limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 140, in search\n",
      "    async for rep in self.search_raw(q, limit=limit, kv=kv):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 136, in search_raw\n",
      "    async for x in self._gql_items(op, kv, limit=limit):\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/api.py\", line 103, in _gql_items\n",
      "    rep = await client.get(f\"{GQL_URL}/{op}\", params=encode_params(params))\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 197, in get\n",
      "    return await self.req(\"GET\", url, params=params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 228, in req\n",
      "    raise e\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/twscrape/queue_client.py\", line 208, in req\n",
      "    rep = await ctx.clt.request(method, url, params=params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1574, in request\n",
      "    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1661, in send\n",
      "    response = await self._send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1689, in _send_handling_auth\n",
      "    response = await self._send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1726, in _send_handling_redirects\n",
      "    response = await self._send_single_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_client.py\", line 1763, in _send_single_request\n",
      "    response = await transport.handle_async_request(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 372, in handle_async_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"/Users/taylory/.local/share/virtualenvs/thesis-hw276cHk/lib/python3.11/site-packages/httpx/_transports/default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known\n"
     ]
    }
   ],
   "source": [
    "# haafu\n",
    "os.mkdir(\"haafu_2022\")\n",
    "scrape_keyword_sampled_tweets(\"2022\", \"ハーフ\", \"haafu\")\n",
    "concatenate_keyword_txt_files(\"2022\", \"haafu\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "import json"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "# filter out 2024 tweet ads\n",
    "total = 0\n",
    "spam = 0\n",
    "with open('zainichi_2022.txt', 'r') as file:\n",
    "    for line in file:\n",
    "        total += 1\n",
    "        tweet = json.loads(line)\n",
    "        # if line == None or tweet == None:\n",
    "        #     not_parsed.append((line, tweet))\n",
    "        #     print(\"Parsing error: \", line, tweet)\n",
    "        # elif tweet['retweetedTweet']:\n",
    "        #     retweets.append(tweet)\n",
    "        #     print(\"Retweet: \", tweet['id'])\n",
    "        if int(tweet['date'].split(\"-\")[0]) > 2022:\n",
    "            spam += 1\n",
    "        # else: \n",
    "            \n",
    "            # tweet_text = tweet['rawContent'] # note: need other prop for over 140 char?\n",
    "            # # preprocess text\n",
    "            # processed = preprocess(tweet_text)            \n",
    "            # # tokenize with mecab\n",
    "            # components = tokenize(processed)\n",
    "            # tokens.append(components)\n",
    "file.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "37483\n",
      "5582\n"
     ]
    }
   ],
   "source": [
    "print(total)\n",
    "print(spam)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "thesis-hw276cHk",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
